// Writes public/js/config.js from environment variables. No dependencies.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const url = (process.env.SUPABASE_URL || "").trim().replace(/\/+$/, "");
const key = (process.env.SUPABASE_ANON_KEY || "").trim();
const isProd = process.env.VERCEL_ENV === "production";

function fail(msg) {
  console.error("\nBuild stopped: " + msg + "\n");
  process.exit(1);
}

if (!url || !key) {
  if (isProd && process.env.ALLOW_DEMO !== "1") {
    fail("SUPABASE_URL and SUPABASE_ANON_KEY must be set for production builds. " +
         "Add them in Vercel > Project > Settings > Environment Variables, then redeploy.");
  }
  console.warn("SUPABASE_URL / SUPABASE_ANON_KEY not set: building in local demo mode.");
} else {
  try {
    const u = new URL(url);
    if (u.protocol !== "https:" && u.hostname !== "localhost" && u.hostname !== "127.0.0.1") throw new Error("not https");
  } catch {
    fail("SUPABASE_URL must be a full https URL, for example https://abcd1234.supabase.co");
  }
  // Never ship a secret key to the browser.
  if (key.startsWith("sb_secret_")) fail("SUPABASE_ANON_KEY looks like a secret key. Use the anon / publishable key.");
  const parts = key.split(".");
  if (parts.length === 3) {
    try {
      const role = JSON.parse(Buffer.from(parts[1], "base64url").toString()).role;
      if (role === "service_role") fail("SUPABASE_ANON_KEY is the service_role key. Use the anon key instead.");
    } catch { /* not a JWT we can read; let it through */ }
  }
}

// Remind the owner about unfinished legal placeholders.
import { readFileSync } from "node:fs";
for (const f of ["privacy.html", "terms.html"]) {
  if (readFileSync(join(root, "public", f), "utf8").includes("[ADD ")) {
    console.warn("WARNING: public/" + f + " still has [ADD ...] placeholders. Fill them in before real users sign up.");
  }
}

const cfg = { supabaseUrl: url, supabaseAnonKey: key };
writeFileSync(
  join(root, "public/js/config.js"),
  "/* Generated by scripts/build.mjs. */\nwindow.PC_CONFIG = " + JSON.stringify(cfg) + ";\n"
);
console.log(url && key ? "Config written: Supabase enabled." : "Config written: demo mode.");
